# Generated by Django 4.1.7 on 2023-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(max_length=8, verbose_name='NCM'),
        ),
    ]
