# Generated by Django 4.1.7 on 2023-04-22 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0002_estoqueentrada_estoquesaida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estoqueitem',
            name='saldo',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
